# Generated by Django 4.1.1 on 2022-11-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
